### ISSUE TITLE
Bayesian RSA needs example and a new version dealing with spatial noise correlation

### ISSUE THREAD

**Issue by lcnature** [IntelPNI/brainiak#109]
Working on them now.
Other issues that I need to work on later: add read_spm to utils.ReadDesign

**Comment by mihaic** [comment]
@lcnature Please add an example as soon as possible.

I should have delayed the PR, but I did not realize it. I am sorry.

**Comment by lcnature** [comment]
Actually it works better this way. Because I changed the code so much, I also need to modify my previous code which calls brsa. With brsa in the package, it is easy to see what needs to be changed.

**Comment by mihaic** [comment]
That is good to hear. However, we should not have code without examples.
