### ISSUE TITLE
Change Random number generator usage and guidelines

### ISSUE THREAD

**Issue by TuKo** [IntelPNI/brainiak#112]
Many methods use random numbers to initialize a structure or run a method.
If many algorithms are ran with the same generator will step one over the other by re-initializing the generator state with a different seed. 

The changes required are the following:

- Each method should have an initial random state. 
- Algorithms should allow to initialize the state from outside to allow deterministic checking.
- Existing algorithms should be modified accordingly.
- Guidelines for contributors and users should be added to the documentation.

**Comment by mihaic** [comment]
Please open separate issues for each algorithm that needs fixing. For the documentation, I opened issue #114.
