### ISSUE TITLE
Documentation issues with some macros (notes, math, etc)

### ISSUE THREAD

**Issue by TuKo** [IntelPNI/brainiak#134]
There are several issues with the macros and the way documentation is being written.
Some math (latex) is rendered incorrectly: see [SSSRM class description](https://pythonhosted.org/brainiak/brainiak.funcalign.html#brainiak.funcalign.sssrm.SSSRM) for an example.

Also the [notes](https://pythonhosted.org/brainiak/brainiak.funcalign.html#brainiak.funcalign.srm.DetSRM) are not shown correctly 

The documentation is available [here](https://pythonhosted.org/brainiak/).

**Comment by lcnature** [comment]
@TuKo It happens to my equations too. I think I just copied my latex text from my paper. How to check the rendering locally before pulling request?

**Comment by TuKo** [comment]
@lcnature, you can create the documentation by calling `make` in the docs subfolder.
Then you open the file ./docs/_build/html/index.html with a browser.

**Comment by mihaic** [comment]
I am working on a PR for this issue.

**Comment by mihaic** [comment]
Fixed by PR #143.
