### ISSUE TITLE
[searchlight] sys.exit used in _get_block_data

### ISSUE THREAD

**Issue by mihaic** [IntelPNI/brainiak#156]
https://github.com/IntelPNI/brainiak/blob/master/brainiak/searchlight/searchlight.py#L136
Instead, an exception should be raised (and documented) in `distribute` if the input data does not have the proper shape.

**Comment by YSanchezAraujo** [comment]
@mihaic are you saying the exception should be raised [here](https://github.com/IntelPNI/brainiak/blob/master/brainiak/searchlight/searchlight.py#L283) instead of [here](https://github.com/IntelPNI/brainiak/blob/master/brainiak/searchlight/searchlight.py#L217)

**Comment by mihaic** [comment]
@YSanchezAraujo, thanks for looking into this issue.

Indeed, I am saying that an exception should be raised in `distribute`, such that the user code can decide what to do, instead of exiting the program as we are doing now. This is the approach we are using everywhere else in BrainIAK.

In practice, in addition to raising an exception in `_get_block_data`, the exception should be caught and a new one raised in `distribute` (so the user does not see the implementation details in the traceback).

Instead, it would be simpler to check the input shape in `distribute` and just remove the `else` code from `_get_block_data`.

**Comment by YSanchezAraujo** [comment]
thanks for the response, some questions:

is the `mask` argument guaranteed to be a numpy array, and or the 4d arrays inside `subjects`, should there be an instance check and maybe a `np.array(<argument>)` if `isinstance(<argument>, np.ndarray)` returns false?

**Comment by mihaic** [comment]
We should also check `mask`. And arguments should be `np.ndarray` instances. It is better if users explicitly apply `np.array` to other data structures themselves and deal with potential issues.
