### ISSUE TITLE
error thrown in searchlight example

### ISSUE THREAD

**Issue by judithfan** [IntelPNI/brainiak#185]
Searchlight example (brainiak/examples/searchlight/example_searchlight.py) throws error when trying to execute:

>>> sl.distribute([data_1], mask_1)

TypeError: distribute() missing 1 required positional argument: 'mask'

Not exactly sure why the mask argument is considered to be missing, since it is provided. Any ideas?

**Comment by mihaic** [comment]
I cannot reproduce the error by executing the example. From what you wrote, it looks like you are executing code based on the example, not specifically the example (`data_1` instead of `data`). Could you please try to execute the example and let us know if you still see the error? Make sure your BranIAK installation is up to date (`pip install -U brainiak`).

**Comment by judithfan** [comment]
Hi Mihai,
Thanks. Ah -- I copied in my 2nd attempt to run a snippet of the example code elsewhere, but even when trying to execute the example code exactly (copied into a notebook), I get this error: 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-67e38076cae1> in <module>()
      3 
      4 # Distribute data to processes
----> 5 sl.distribute([data], mask)
      6 sl.broadcast(labels)
      7 

TypeError: distribute() missing 1 required positional argument: 'mask'

**Comment by judithfan** [comment]
I verified that mask is defined and of the proper dimensionality...

**Comment by mihaic** [comment]
I still do not know what is happening. Could you please check the version of BrainIAK you have installed using the following command?
`python3 -m pip freeze --all | grep brain`
Also, could you please run the example directly using the following command?
`python3 example_searchlight.py`

**Comment by judithfan** [comment]
Sure, brainiak version:  
brainiak==0.2.dev63+ng56e70ff

Hmm... it appears to run fine as a script until the plotting steps at the very end. 

Oh! I think I found the issue. Strangely there is a difference between the sl.distribute syntax at line 72 in the example script in the remote repo (https://github.com/IntelPNI/brainiak/blob/master/examples/searchlight/example_searchlight.py):

sl.distribute([data], mask)

vs.
sl.distribute([data], [mask], mask) 

in my freshly pulled version of brainiak. Do you know why that is?

**Comment by mihaic** [comment]
You are using an old version of the code. You should update to the latest version, as I suggested in my first message (`pip install -U brainiak`).

As for updating your local Git repository, make sure you are pulling from IntelPNI and not from your fork.

**Comment by judithfan** [comment]
Hmm, I see. I did run the upgrade, and it appeared to do so successfully. Strange. What should I see when I get the version?

I am pulling from IntelPNI, as I do not have a fork.

**Comment by judithfan** [comment]
I'll try to re-clone & install from scratch.

**Comment by mihaic** [comment]
You should see `brainiak==0.4`. Try uninstalling and installing again.
```
pip uninstall brainiak
pip install brainiak
```

**Comment by judithfan** [comment]
Got it -- thanks!
