### ISSUE TITLE
test_sssrm.py crashing run-tests.sh

### ISSUE THREAD

**Issue by cbaldassano** [IntelPNI/brainiak#186]
When running ./run-tests.sh on my local machine (or running ./pr-check.sh), I receive an error message during the tests on sssrm (error log below). I am running MacOS 10.12 with Python 3.5.2.

pip freeze | grep -qi /brainiak || {
    echo "You must install brainiak in editable mode using \"pip install -e\""`
        `" before calling "$(basename "$0")
    exit 1
}

mpi_command=mpiexec
if [ ! -z $SLURM_NODELIST ]
then
    mpi_command=srun
fi
$mpi_command -n 2 coverage run -m pytest
============================= test session starts ==============================
platform darwin -- Python 3.5.2, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /Users/chrisb/brainiak, inifile: 
============================= test session starts ==============================
platform darwin -- Python 3.5.2, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /Users/chrisb/brainiak, inifile: 
collected 45 items

tests/eventseg/test_event.py .collected 45 items

tests/eventseg/test_event.py ....
tests/factoranalysis/test_htfa.py .
tests/factoranalysis/test_htfa.py ......
tests/factoranalysis/test_tfa.py 
tests/factoranalysis/test_tfa.py .
tests/fcma/test_classification.py ..
tests/fcma/test_classification.py .
tests/fcma/test_io.py ..
tests/fcma/test_io.py .......
tests/fcma/test_mvpa_voxel_selection.py .
tests/fcma/test_mvpa_voxel_selection.py .
tests/fcma/test_util.py .
tests/fcma/test_voxel_selection.py .
tests/fcma/test_util.py .
tests/fcma/test_voxel_selection.py ....
tests/funcalign/test_srm.py 
tests/funcalign/test_srm.py ....
tests/funcalign/test_sssrm.py 
tests/funcalign/test_sssrm.py ....
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 13045 RUNNING AT nat-oitwireless-inside-vapornet100-b-30955.Princeton.EDU
=   EXIT CODE: 4
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Illegal instruction: 4 (signal 4)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions

**Comment by mihaic** [comment]
That code has not changed in a while. Do you get the error consistently? Do you have the latest code from master or the latest version on PyPI?

**Comment by cbaldassano** [comment]
Hmm, this was happening consistently but after the recent merge it seems to have resolved. I'll close this as nonreproducible for now.
