### ISSUE TITLE
install latest version (dev)/cannot get cython_blas.pyx 

### ISSUE THREAD

**Issue by rschmaelzle** [IntelPNI/brainiak#187]
Hi,
I've been trying out brainiak and did succeed to install via 'pip3 install -U brainiak'. However, I then run into a conflict:

> /usr/local/lib/python3.6/site-packages/brainiak/fcma/util.py in <module>()
>      21 
>      22 import numpy as np
> ---> 23 from . import cython_blas as blas
>      24 from scipy.stats.mstats import zscore
>      25 import math
> 
> ImportError: cannot import name 'cython_blas'

In my site-package folder, the brainiak v0.4 has in its fcma folder some other files (e.g. cython_blas.cpython-36m-darwin.so), which seem to be relics of an older version. Or I am doing sth wrong...
 
I've been trying all sorts of things, including an install from the latest git-master branch. That did not work out fully either, although that way I can obtain the cython_blas.pyx and it mentions a more recent version brainiak-0.5.dev20+ng7940c62. Is there any remedy that would help me get started? I am working on a Mac OsX El Captitan, using conda and python3.5.
Thanks a lot , Best, Ralf.

**Comment by yidawang** [comment]
`cython_blas` is a cython file which should be in your site-package folder. The `.so` file is the compiled dynamic library which is also normal to be there. Can you verify both files are at `/usr/local/lib/python3.6/site-packages/brainiak/fcma/`? BTW, you said you use conda and python3.5, which doesn't seem to be consistent with the folder name in your error message snippet?

**Comment by rschmaelzle** [comment]
thanks for the reply. 
you wre right about python version. I had misnamed the environment as py35, but it runs python 3.6. 

the files cython_blas.cpython-36m-darwin.so and fcma_extension.cpython-36m-darwin.so are in the folder. However, the github-master repo had cython_blas.pyx in the fcma folder, and also the isfc.py file in the top folder. both did not get installed (probably because they are not in v0.4), and so I could not run the isfc example, which was what got me in trouble. If there is a way to get this development version installed, that would be great. I tried to download the master-branch as zip (which included the isfc) and then run python install -e , and it completed, but then I couldnt import the modules. If it is not possible now, I'll have to wait. Thanks Ralf.

**Comment by yidawang** [comment]
I am sure `cython_blas.pyx` is in v0.4. Can you turn on the verbose flag and redo the installation to see if the files are correctly copied?

You can do `pip install git+https://github.com/IntelPNI/brainiak` to install the latest development version.

**Comment by rschmaelzle** [comment]
Hi, thanks. I just did, but again cannot obtain cython_blas.pyx. I attach copy of the output and a screenshot of the result folder. 

I did already try the tip with pip install git+... . (with pip it throws an error, but pip3 works). In that case I do get the isfc.py, which was recently added. However, even with this version there is still no cython_blas.pyx in the fcma folder (which I assume should be the case) and running the isfc example throws an error that it does not find cython_blas.
Best, r


<img width="608" alt="screen shot 2017-02-27 at 12 52 48 am" src="https://cloud.githubusercontent.com/assets/7194492/23350216/1596b12c-fc87-11e6-8ce7-dcbf764c5033.png">

[report.txt](https://github.com/IntelPNI/brainiak/files/802742/report.txt)

**Comment by yidawang** [comment]
I checked my folder, `cython_blas.pyx` isn't there since the `cython_blas*.so` file has been compiled. Sorry for the confusion.

But, I just installed the latest development code and run the isfc example, everything looks good to me. Can you double check your `cython_blas.cpython-36m-darwin.so` is successfully compiled?

**Comment by rschmaelzle** [comment]
cython_blas.cpython-36m-darwin.so is in the folder. Does that mean it is successfully compiled?
If I try to run the example, however, it fails at the import of cython_blas. Not exactly sure how to check that. 
<img width="759" alt="screen shot 2017-02-27 at 1 23 25 am" src="https://cloud.githubusercontent.com/assets/7194492/23350868/83b14c22-fc8b-11e6-9738-688539e507c9.png">

**Comment by yidawang** [comment]
try `otool -L cython_blas.cpython-36m-darwin.so`?

**Comment by rschmaelzle** [comment]
ok, just did. it gives me this: 
(pybrainiak) cas3401schmaelzle:fcma Ralf$ otool -L cython_blas.cpython-36m-darwin.so
cython_blas.cpython-36m-darwin.so:
	/usr/local/opt/llvm/lib/libomp.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
(pybrainiak) cas3401schmaelzle:fcma Ralf$ 
will look into it. best, r

**Comment by yidawang** [comment]
hmmm. Everything looks good to me. We may need fresh eyes...

**Comment by rschmaelzle** [comment]
ok, thanks I will try some things and search a bit.

**Comment by rschmaelzle** [comment]
I found the mistake. Sorry, but it turned out to be entirely on my side. The kernel from which I ran the notebook was 3.6, but not the right environment that installed brainiak. So I had to get that kernel added to the notebook, which is cumbersome of its own, but again, did not seem to interact with brainiak. For the record, this was what got it solved:

> conda install notebook or conda install ipykernel
> ipython kernel install --name pybrainiak
> 

best, r

**Comment by allisonjberman** [comment]
@rschmaelzle I think I'm having the same issue. I tried what you posted, but I am still unable to import: from . import cython_blas as blas
import brainiak.eventseg.event

Is there anything else you did? Thanks!

**Comment by rschmaelzle** [comment]
@allisonjberman i am afraid I don't fully remember. Are you sure you have all the files on your system (i.e. the bleeding edge version and can see the cython_blas files? - i only vaguely remember there was sth with versions/master branch etc..). 
If you have those (which I had finally managed), then the critical issue was activating the right environment (i.e. the 3.6 version) and running the notebook on that (rather than from my 2.7. install) Thanks

**Comment by mihaic** [comment]
@allisonjberman, I would be happy to chat on Gitter if you would like to troubleshoot your installation:
https://gitter.im/IntelPNI/brainiak
