### ISSUE TITLE
Broadcast variable should be optional

### ISSUE THREAD

**Issue by jamalw** [IntelPNI/brainiak#200]
Without specifying broadcast variables you get an error:

AttributeError: 'Searchlight' object has no attribute 'bcast_var' 

Sometimes, there is no need to specify a broadcast variable so we should have the option to not have to specify it.

**Comment by mjanderson09** [comment]
Thank you Jamal. This was resolved in #221

**Comment by jamalw** [comment]
Awesome!

- Jamal
