### ISSUE TITLE
instruction for updating package, installing brainiak in anaconda, and ways to easily get examples

### ISSUE THREAD

**Issue by lcnature** [IntelPNI/brainiak#227]
I realize that for users who are less familiar with python, it might not even be intuitive of how to update brainiak package. It might be worth adding a few lines of this in the readme.

Also, is it easier for new python users to use anaconda? Do we need instruction of how to install brainiak if one goes with anaconda?

And I think it might not be intuitive for users who just installed brainiak to discover where the examples are. Because I am always running it in developing mode, I myself do not know whether I am supposed to download the example files from github in addition after installing brainiak with pip, if I were just a new user.
Perhaps a readme in the example page (https://github.com/IntelPNI/brainiak/tree/master/examples) would be at least helpful?

**Comment by mihaic** [comment]
See issues #228 and #229 for the parts about examples and updating. The current installation instructions work for Anaconda users.
