### ISSUE TITLE
Document update procedure

### ISSUE THREAD

**Issue by mihaic** [IntelPNI/brainiak#229]

**Comment by lcnature** [comment]
Is it possible to have some script in brainiak that checks whether the version of brainiak installed is significantly old? Partially related to this: a user pointed to me a bug which I fixed long time before and we found out that he was using a previous version. It might be that pip has a delay in updating its archive. But it would be nice in future if we can give a warning to a user who is using a buggy old version when an update to the new version is recommended.

**Comment by mihaic** [comment]
Pip already supports this:
https://pip.pypa.io/en/stable/reference/pip_list/#cmdoption-o
```
python3 -m pip list --outdated
```

**Comment by lcnature** [comment]
I see, I guess I was asking the possibility of automatically checking this
for the user whenever a module in brainiak is imported. Users might not
want to often check version manually, or may not be aware that a bug exists
in the version he/she is using.

Mingbo Cai

**Comment by mihaic** [comment]
I agree that it would be nice to be notified of new versions, but this type of automatic checking belongs to Pip, not BrainIAK (and all other Python packages).

**Comment by lcnature** [comment]
I see. Thanks!

Mingbo Cai
