### ISSUE TITLE
brsa: Warnings should not be ignored without justification

### ISSUE THREAD

**Issue by mihaic** [IntelPNI/brainiak#237]
It would be best to remove the filter. If not possible, please add an explanation and restrict the filter to the scope where it is needed.
https://github.com/IntelPNI/brainiak/blob/master/brainiak/reprsimil/brsa.py#L40

**Comment by lcnature** [comment]
Thanks. Just did it in the current PR being reviewed.

**Comment by mihaic** [comment]
Fixed by #239.
