### ISSUE TITLE
searchlight: Add minimum percentage of masked voxels

### ISSUE THREAD

**Issue by mihaic** [IntelPNI/brainiak#251]
Currently, we run the searchlight function on all voxels that have at least one active neighbor according to the mask. Some users are accustomed to setting a higher minimum required percentage of active neighboring voxels, e.g., 50%. We should offer an option.

**Comment by hcchang73** [comment]
Such an option will definitely be useful to me!

**Comment by mihaic** [comment]
While implementing this, I realized it is fits better in the searchlight function itself. The function has access to the mask, so it can easily test the proportion of active voxels and return `None` if it less than the desired minimum. If adding it to the searchlight framework, it becomes an extra parameter to pass around, which makes the API convoluted. What do you think, @hcchang73, @mjanderson09?

**Comment by hcchang73** [comment]
It sounds good to me.
We might need a default value, e.g. 50%.

Best,
 -----------------------------------------------------------
張惠娟
Claire Hui-Chuan Chang
Princeton Neuroscience Institute
huichuan@princeton.edu
+12017458684

**Comment by mihaic** [comment]
Here is an example of to better illustrate what I have in mind:
```python
def searchlight_function_with_threshold(data, mask, broadcast_variable):
    if np.count_nonzero(mask) / mask.size < 0.5:
        return None
    return useful_computation(data)
output = sl.run_searchlight(searchlight_function_with_threshold)
```
This way, `sl` does not need to know about the `0.5`.

**Comment by hcchang73** [comment]
Hello, Mihai

This looks fine to me, as long as it's easy for the user to access or even
change the threshold.
It means that the definition of "searchlight_function_with_threshold" is
easy to find or threshold is an explicit argument.



Best,
 -----------------------------------------------------------
張惠娟
Claire Hui-Chuan Chang
Princeton Neuroscience Institute
huichuan@princeton.edu
+12017458684
