### ISSUE TITLE
factoranalysis MPI error when fitting HTFA to datasets with 3+ subjects on a single machine

### ISSUE THREAD

**Issue by jeremymanning** [IntelPNI/brainiak#259]
When fitting HTFA to a dataset with >2 nifti files, the code throws the following exception:
```
Exception: Message truncated, error stack:
PMPI_Gather(904)......: MPI_Gather(sbuf=0x233da90, scount=60, MPI_DOUBLE, rbuf=0x2ef1220, rcount=40, MPI_DOUBLE, root=0, MPI_COMM_WORLD) failed
MPIR_Gather_impl(726).: 
MPIR_Gather(686)......: 
MPIR_Gather_intra(187): 
MPIR_Localcopy(74)....: Message truncated; 480 bytes received but buffer size is 320
```

Here's a [Jupyter notebook](http://discovery.dartmouth.edu/~jmanning/pniintel/htfa_mpi_error.ipynb) and a [docker container](https://github.com/Summer-MIND/mind-tools) for reproducing this error.  The notebook shows that HTFA runs successfully when fitting a dataset with 2 subjects, but then errors with the above message when fitting a dataset with 3 subjects.  The link to the docker container also contains installation instructions.

**Comment by mihaic** [comment]
Thank you for the detailed report. We are looking into it.

**Comment by xiazhu** [comment]
In HTFA, there is an input parameter n_subj, the default value is 2. When running HTFA with different number of subjects, please configurable this parameter.  For example, when a dataset contains 3 subjects, please use htfa = HTFA(K=5,n_subj=3) rather than htfa = HTFA(K=5)

**Comment by jeremymanning** [comment]
could we automatically set the `n_subj` parameter based on len(input), when `fit` is called?

**Comment by xiazhu** [comment]
we cannot. with MPI, each process knows how many subjects it gets, but does not know how many other process get.

**Comment by mihaic** [comment]
@xiazhu, I think we should remove the default value for `n_subj`, given that I do not see any reason why `2` (or any other value) makes sense. What do you think?

**Comment by xiazhu** [comment]
@mihaic yes, works fine for me.
