### ISSUE TITLE
searchlight: outputs more than a 3d array?

### ISSUE THREAD

**Issue by hcchang73** [IntelPNI/brainiak#265]
Hello,

I use searchlight to compare the activation pattern in each cube to a predicted pattern (correlation).
To do my statistic analysis, I also permute the data for 1000 iterations to get the null distribution.
My problem is that, the output of searchlight is a 3D imaging, e.g. z-value, but I need more than one outputs. 
For example, I might need the r-value, the z-value, and the std of the null distribution in each cube.
I also need the maximum r-value across voxels in each iteration. Therefore, a 4D outputs with dimension 4 equals the number of iteration might be useful.

Is it possible to get a 4D output from searchlight? 

Thanks.

**Comment by mihaic** [comment]
The searchlight result can contain arbitrary (pickle-able) Python objects. So you could return a tuple containing all the values you are interested in from your searchlight function.

**Comment by hcchang73** [comment]
I tried and failed.
Could you give me an example.
And below is my codes:
>>> def rsa_perm(fmri,msk,myrad,bcast_var):
...     fmri = np.array(fmri)
...     fmri = fmri.reshape((-1,fmri.shape[-1]))
...     fmri=fmri[~np.isnan(fmri).any(axis=1)] # remove rows containing NA
...     fmriSim = np.corrcoef(fmri,rowvar=0)
...     r_p = np.corrcoef(np.concatenate(fmriSim),np.concatenate(textSim))[0,1]
...
...     np.random.seed(0)
...     r_perm_holder = []
...     for i in range(iteration):
...         fmriSim_perm=np.random.permutation(fmriSim)
...         fmriSim_perm=np.random.permutation(fmriSim.T).T
...         r_p_perm = np.corrcoef(np.concatenate(fmriSim_perm),np.concatenate(textSim))[0,1]
...         r_perm_holder.append(r_p_perm)
...     std=np.std(r_perm_holder)
...     z = (r_p - np.mean(r_perm_holder))/np.std(r_perm_holder)
...     return r_p, std, z
...
>>> sl = Searchlight(sl_rad=rad,max_blk_edge=10) # rad unit is voxel
>>> sl.distribute([fmri_datam_zscore_4d],roi_img)
>>> sl.broadcast(textSim)
>>> print('Running Searchlight...')
Running Searchlight...
>>>
>>> r, std, z = sl.run_searchlight(rsa_perm)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/jukebox/pkgs/ANACONDAPY/ni/lib/python3.6/site-packages/brainiak/searchlight/searchlight.py", line 378, in run_searchlight
    return self.run_block_function(_singlenode_searchlight)
  File "/jukebox/pkgs/ANACONDAPY/ni/lib/python3.6/site-packages/brainiak/searchlight/searchlight.py", line 294, in run_block_function
    for (idx, mypt) in enumerate(self.blocks)]
  File "/jukebox/pkgs/ANACONDAPY/ni/lib/python3.6/site-packages/brainiak/searchlight/searchlight.py", line 294, in <listcomp>
    for (idx, mypt) in enumerate(self.blocks)]
  File "/jukebox/pkgs/ANACONDAPY/ni/lib/python3.6/site-packages/brainiak/searchlight/searchlight.py", line 373, in _singlenode_searchlight
    outmat[i, j, k] = outlist[cnt]
ValueError: cannot copy sequence with size 3 to array axis with dimension 1

**Comment by mihaic** [comment]
Looking at the last line in the traceback you posted (`outmat[i, j, k] = outlist[cnt]`), I think you are using an old version of BrainIAK. Could you please upgrade before continuing testing?

Finally, note that `run_searchlight` will return a single array that has multiple values in each element, as opposed to multiple arrays, so you will not be able to write `r, std, z = sl.run_searchlight(rsa_perm)`.

**Comment by hcchang73** [comment]
Ur...So what function should I use instead of "run_searchlight??"

**Comment by mihaic** [comment]
You should use `run_searchlight`. As you saw, the output is a 3D array. Each element of that array is a tuple containing `r_p, std, z`, the elements you return in your searchlight function, `rsa_perm`.

**Comment by hcchang73** [comment]
I finally got it right!
The problem with my testing is that the mask I used contains NaN.
Therefore, only one NaN value is returned.
It works now. 

Thanks a lot! :)

**Comment by mihaic** [comment]
Happy to help. :)

FYI, I created another issue (issue #267) about adding an example that deals with multiple return values to make it easier for others in the future.
