### ISSUE TITLE
Have continuous integration detailed results visible to the public

### ISSUE THREAD

**Issue by mihaic** [IntelPNI/brainiak#63]
Either make public the existing Jenkins results or add more servers, e.g., travis-ci.org.

**Comment by cameronphchen** [comment]
+1 for using travis-ci.org. I would love to see publicly visible CI results, and I can help with setting this up.

**Comment by mihaic** [comment]
Thanks for the offer to help, Cameron. I added the hook. If you make a pull request with a `.travis.yml`, I will be happy to accept it.

**Comment by mihaic** [comment]
Closed by #85.
