### ISSUE TITLE
error in C++ compilation on MacOS

### ISSUE THREAD

**Issue by yidawang** [IntelPNI/brainiak#83]
There are building errors with `pyport.h` using the new `clang`. It is a documented [python bug](http://bugs.python.org/issue10910)

A workaround solution is to edit `pyport.h` file by adding two lines. 

> diff --git a/Include/pyport.h b/Include/pyport.h
> --- a/Include/pyport.h
> +++ b/Include/pyport.h
> @@ -699,6 +699,12 @@
>  #endif
>  
>  #ifdef _PY_PORT_CTYPE_UTF8_ISSUE
> +#ifndef __cplusplus
>  #include <ctype.h>
>  #include <wctype.h>
>  #undef isalnum
> @@ -716,6 +722,7 @@
>  #undef toupper
>  #define toupper(c) towupper(btowc(c))
>  #endif
> +#endif
>  
>  
>  /* Declarations for symbol visibility.

The `pyport.h` file is at `/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/include/python3.5m/` if you use `brew` to install `python3`.

**Comment by mihaic** [comment]
Fixed upstream:
https://github.com/Homebrew/homebrew-core/commit/84897ff215081998c8bc17cc663320ae50f7ccf4
